spring:
  jpa:
    database: postgresql
    show-sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

database:
  provider: postgresql
  url: localhost
  port: 5432
  name: rinha_backend
  username: postgres
  password: 12345